services:
  ingress:
    restart: always
    image: nginx:latest
    volumes:
      - './deployment/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '8877:80'
    depends_on:
      - frontend
      - backend
  frontend:
    restart: always
    image: rafaelottersberg/jassapp-frontend
    build:
      dockerfile: Dockerfile
      context: .
  backend:
    restart: always
    image: rafaelottersberg/jassapp-backend
    build:
      dockerfile: Dockerfile
      context: backend
    volumes:
      - './backend/api:/app/api'
    depends_on:
      - db
    env_file:
      - './secrets.env'
    environment:
      IMAGE_SIZE: 800
      IMAGE_QUALITY: 85
      WORKERS: 1
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: jassapp
      POSTGRES_DB: jassapp
  db:
    restart: always
    image: postgres:16-alpine
    volumes:
      - jassapp-db-data:/var/lib/postgresql/data
    env_file:
      - './secrets.env'
    environment:
      POSTGRES_USER: jassapp
      POSTGRES_DB: jassapp

volumes:
  jassapp-db-data:
