export const bezirksListe = [
  '3x3 (Region Lenzburg)',
  'Aarau',
  'Aarau Arabische Gemeinde',
  'Adliswil-Zürich 2',
  'Wollishofen Projekt Regenbogenkirche',
  'Affoltern a.A.',
  'Baden',
  'Basel-Allschwilerplatz',
  'Basel-Ost',
  'Basel-Kleinbasel',
  'Biel',
  'Burgdorf-Breitenegg',
  'Büren-Grenchen',
  'Gelterkinden',
  'Gerlafingen',
  'Kirche anders',
  'Liestal',
  'Lyss-Aarberg',
  'Muhen',
  'Region Oberaargau',
  'Region Zimmerberg',
  'Rothrist',
  'Solothurn',
  'Vorstatt Chele Bottenwil',
  'Windisch-Brugg',
  'Zofingen',
  'Belp',
  'Bern',
  'Frutigland',
  'Gstaad',
  'Interlaken',
  'Lenk',
  'Oberemmental',
  'Schlatt',
  'Schwarzenburg',
  'Spiez-Oey',
  'Thun-Heiligenschwendi',
  'Worb',
  'Bäretswil-Uster-Dübendorf',
  'Bregenz',
  'Bülach-Oberglatt',
  'Chur',
  'Davos',
  'Embrachertal',
  'Eschlikon',
  'Glarus',
  'Herisau',
  'Klingenberg-Kreuzlingen',
  'Kloten-Glattbrugg',
  'Region Schaffhausen',
  'Rhein-Bodensee',
  'Romanshorn',
  'Rüti-Wald-Hombrechtikon',
  'St. Gallen-Teufen',
  'Sevelen',
  'Stäfa-Männedorf',
  'Turbenthal-Russikon',
  'Uzwil-Flawil',
  'Frauenfeld-Weinfelden',
  'Winterthur',
  'Wyland ZH',
  'Zürich-Altstetten',
  'Zürich-Nord',
  'Zürich-Ost',
  'Zürich 4',
  'andere',
];
