"""multi-game invites and invite codes

Revision ID: 5c219b71d3a1
Revises: 14a3d6dbfb86
Create Date: 2026-08-23 22:18:21.056062

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c219b71d3a1'
down_revision = '14a3d6dbfb86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('used_by_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_codes_code'), ['code'], unique=True)

    op.create_table('game_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'user_id', name='uq_game_participant')
    )
    with op.batch_alter_table('game_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_participants_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_participants_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)

    # ### end Alembic commands ###

    # Data cleanup: games from the old single-active-game model have no
    # game_participants rows and can't function under the new per-game
    # roster model, so archive them rather than leaving them stuck 'active'
    # with nobody able to see or play them.
    op.execute("""
        UPDATE games
        SET status = 'finished'
        WHERE status = 'active'
          AND id NOT IN (SELECT DISTINCT game_id FROM game_participants)
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)

    with op.batch_alter_table('game_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_participants_game_id'))

    op.drop_table('game_participants')
    with op.batch_alter_table('invite_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_codes_code'))

    op.drop_table('invite_codes')
    # ### end Alembic commands ###
